const base = "chapter-06/";

const htmls = [
  { description: '', name: '06-01-position-absolute-comments.html' },
  { description: '', name: '06-05-position-absolute-overlay-sizing.html' },
  { description: '', name: '06-09-floated-image-nudge.html' },
  { description: '', name: '06-10-floated-image-sidebyside.html' },
  { description: '', name: '06-11-floated-image-sidebyside-reverse.html' },
  { description: '', name: '06-19-inline-block-article-share.html' },
  { description: '', name: '06-20-inline-block-navbar-broken.html' },
  { description: '', name: '06-21-1-table-display-navbar.html' },
  { description: '', name: '06-21-inline-block-navbar-fontfix.html' },
  { description: '', name: '06-22-table-display-navbar-vertical-align.html' },
  { description: '', name: '06-24-flexbox-navbar-nowidth.html' },
  { description: '', name: '06-25-flexbox-navbar-row-reverse.html' },
  { description: '', name: '06-26-flexbox-navbar-justify-flexend.html' },
  { description: '', name: '06-27-flexbox-navbar-justify-center.html' },
  { description: '', name: '06-28-flexbox-navbar-justify-spacebetween.html' },
  { description: '', name: '06-29-flexbox-navbar-justify-spacearound.html' },
  { description: '', name: '06-30-flexbox-navbar-marginauto.html' },
  { description: '', name: '06-31-flexbox-navbar-align-stretch.html' },
  { description: '', name: '06-32-flexbox-navbar-align-start.html' },
  { description: '', name: '06-33-flexbox-navbar-align-center.html' },
  { description: '', name: '06-34-flexbox-navbar-align-end.html' },
  { description: '', name: '06-35-flexbox-navbar-align-baseline.html' },
  { description: '', name: '06-36-flexbox-navbar-align-self.html' },
  { description: '', name: '06-37-flexbox-vertical-centering.html' },
  { description: '', name: '06-38-flexbox-vertical-centering-author-info.html' },
  { description: '', name: '06-44-flexbox-navbar-flexsize-grow-2-1.html' },
  { description: '', name: '06-47-flexbox-taglist-wrap.html' },
  { description: '', name: '06-48-flexbox-taglist-wrap-row-reverse.html' },
  { description: '', name: '06-49-flexbox-taglist-wrap-reverse-row-reverse.html' },
  { description: '', name: '06-50-flexbox-taglist-wrap-flex.html' },
  { description: '', name: '06-52-flexbox-taglist-wrap-flex-max-width.html' },
  { description: '', name: '06-53-1-flexbox-taglist-wrap-align-content-flex-end.html' },
  { description: '', name: '06-53-flexbox-taglist-wrap-align-content-stretch.html' },
  { description: '', name: '06-54-flexbox-column-order-teaser.html' },
  { description: '', name: '06-57-flexbox-nested-teasers-auto-margin.html' },
  { description: '', name: '06-XX-flexbox-navbar-width.html' },
  { description: '', name: '06-XX-positioning-stacking-context.html' }
]