const base = "./html/"
const htmls = {
  04: { filename: "05-04-finished-example.html", description: "" },
  05: { filename: "05-05-initial-header-example.html", description: "" },
  06: { filename: "05-06-bigger-image-header-example.html", description: "" },
  08: { filename: "05-08-new-background-position-syntax.html", description: "" },
  09: { filename: "05-09-background-clip.html", description: "" },
  10: { filename: "05-10-fixed-background-attachment.html", description: "" },
  11: { filename: "05-11-background-size-percentages.html", description: "" },
  13: { filename: "05-13-background-size-cover-position.html", description: "" },
  14: { filename: "05-14-multiple-backgrounds.html", description: "" },
  16: { filename: "05-16-border-profile-example.html", description: "" },
  17: { filename: "05-17-border-radius-single-corner.html", description: "" },
  18: { filename: "05-18-border-radius-circle.html", description: "" },
  19: { filename: "05-19-pill-shape-obrund.html", description: "" },
  20: { filename: "05-20-border-image.html", description: "" },
  22: { filename: "05-22-box-shadow-profile-photo.html", description: "" },
  25: { filename: "05-25-multiple-shadows-zero-blur.html", description: "" },
  26: { filename: "05-26-linear-gradient-profile-box.html", description: "" },
  27: { filename: "05-27-linear-gradient-diagonal-profile-box.html", description: "" },
  28: { filename: "05-28-radial-gradient-profile-box.html", description: "" },
  29: { filename: "05-29-radial-gradient-profile-box-defaults.html", description: "" },
  30: { filename: "05-30-repeating-gradients.html", description: "" },
  32: { filename: "05-32-repeating-pattern.html", description: "" },
  35: { filename: "05-35-img-maxwidth.html", description: "" },
  37: { filename: "05-37-object-fit.html", description: "" },
}